# Generated by Django 2.2.2 on 2019-06-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_auto_20190616_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
