# Generated by Django 2.2.2 on 2019-06-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_auto_20190616_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='publisher_id',
        ),
    ]
